name: workflow-unit-molnet

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - uses: goanpeca/setup-miniconda@v1
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda install -c conda-forge nose2
        wget https://data.qiime2.org/distro/core/qiime2-2019.7-py36-linux-conda.yml
        conda env create -n qiime2-2019.7 --file qiime2-2019.7-py36-linux-conda.yml
        conda activate qiime2-2019.7
        pip install xmltodict
        pip install pyMolNetEnhancer
        pip install metabodisttrees
    - name: Test with nose2
      shell: bash -l {0}
      run: |
        cd molnetenhancer/test && nose2 -v && cd ../..
