name: workflow-unit-fbmn

on: [push]

jobs:
  test-fbmn:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        pip install pathlib
        pip install -r requirements.txt
    - name: Test with nose2
      run: |
        pip3 install nose2
        cd feature-based-molecular-networking/test && nose2 -v
